#!/bin/bash

set -euo pipefail

state_dir="${XDG_STATE_HOME:-$HOME/.local/state}/winblues/xfconf-profile"
mkdir -p ${state_dir}

# Abnormal case -- just delete the state_dir and start over
if [ ! -d ${state_dir}/booted ] && [ -d ${state_dir}/previous ]; then
  echo "Invalid state: resetting data"
  rm -rf ${state_dir}
fi

# First run
if [ ! -d ${state_dir}/booted ] && [ ! -d ${state_dir}/previous ]; then
  echo "Empty state"
  mkdir -p ${state_dir}/booted
  cp /usr/share/xfconf-profile/default.json ${state_dir}/booted/profile.json
  exit 0
fi

# Steady run
if [ -d ${state_dir}/booted ]; then
  echo "Steady state"
  rm -rf ${state_dir}/previous
  mv ${state_dir}/{booted,previous}

  mkdir -p ${state_dir}/booted
  cp /usr/share/xfconf-profile/default.json ${state_dir}/booted/profile.json

  # If the configurations changed
  if diff -q ${state_dir}/{booted,previous}/profile.json > /dev/null;
    echo "Configurations differ -- reverting old and applying new"
    xfconf-profile revert ${state_dir}/previous/profile.json
    xfconf-profile apply ${state_dir}/booted/profile.json
  else
    echo "Configurations identical -- no changes required"
  fi
fi
